kind: pipeline
name: default

steps:
  - name: Lint
    image: python:3.7-alpine
    commands:
      - apk add --no-cache make
      - make lint

  - name: Unit test
    image: docker:dind
    commands:
      - apk add --no-cache make
      - make unit-tests
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Run API tests
    image: docker:dind
    commands:
      - apk add --no-cache make util-linux
      - make api-test
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Build Image
    image: docker:dind
    commands:
      - make build-image
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Push Image
    image: docker:dind
    commands:
      - make push-image
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
