version: '3.5'

services:
  server:
    image: estimations-api
    build:
      context: .
      labels:
        Project: Estimations
    expose:
      - 5000
    env_file:
      - ./env.d/app.env
      - ./env.d/app.db.env
    networks:
      - scrum-apis
    depends_on:
      - db

  migrations:
    image: estimations-api
    build:
      context: .
      labels:
        Project: Estimations
    command:
      - migrate
    env_file:
      - ./env.d/app.env
      - ./env.d/app.db.env
    networks:
      - scrum-apis
    depends_on:
      - db

  db:
    image: mysql:5.7
    expose:
      - 3306
    networks:
      - scrum-apis
    env_file:
      - ./env.d/db.env

networks:
  scrum-apis:
    external:
      name: scrum-apis
