version: '3.5'
services:

  server:
    command:
      - develop
    ports:
      - 5000:5000
      - 6899:6899
    environment:
      FLASK_ENV: development
      FLASK_APP: run
    volumes:
      - ./requirements-dev.txt:/app/requirements-dev.txt
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./bin/:/app/bin/
      - ./src/:/app/src/
      - ./migrations/:/app/migrations/

  migrations:
    command:
      - migrate
    volumes:
      - ./bin/:/app/bin/
      - ./src/:/app/src/
      - ./migrations/:/app/migrations/
      - ./entrypoint.sh:/app/entrypoint.sh

  db:
    ports:
      - 3306:3306
    volumes:
      - estimations-db:/var/lib/mysql

volumes:
  estimations-db:
